defaults:
  - _self_

seed: 42
embed_size: 20
frame_width: 850
frame_height: 850

data:
  challenge_name: "mabe-2022-mouse-triplets"
  data_dir: "data"
  paths:
    base_dir: "${hydra:runtime.cwd}"
    dataset_dir: "${data.paths.base_dir}/datasets"
    submission_dir: "${data.paths.base_dir}/submissions"
    visualizations_dir: "${data.paths.base_dir}/visualizations"

visualization:
  mouse_colors:
    - "lawngreen"
    - "skyblue"
    - "tomato"
  plot_pairs: [[0, 1], [1, 3], [3, 2], [2, 0],
               [3, 6], [6, 9],
               [9, 10], [10, 11],
               [4, 5], [5, 8], [8, 9], [9, 7], [7, 4]] 